name: build

on: [push, pull_request]

jobs:
  test:
    name: Test on node ${{ matrix.node-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        cache: 'npm'
        node-version: ${{ matrix.node-version }}
    - name: npm ci
      run: npm ci
    - name: npm run lint
      run: npm run lint
    - name: npm test
      run: npm test
    